# Generated by Django 5.2.11 on 2026-03-02 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_clinician'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinician_id_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated clinician identifier, e.g. C-000001', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patient_id_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated patient identifier, e.g. P-000001', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='clinician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'clinician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
